---
label: Recipe
hide_body: false
fields:
- type: text
  name: author
  label: Author
  hidden: true
  default: Monika Godelienė
  config:
    required: true
- type: text
  name: layout
  label: Layout
  hidden: true
  default: post
  config:
    required: true
- type: text
  name: title
  label: Title
- type: datetime
  name: date
  label: Date
  default: now
  config:
    required: true
- type: file
  name: cover
  label: Cover
- name: tags
  type: tag_list
  default: []
  label: Tags
pages:
- _posts/2020-08-20-cannelloni-idaryti-rikota-ir-moliugu.md
- _posts/2020-08-22-avinzirniu-makaronai-su-mocarela.md
- _posts/2020-08-24-vistienos-troskinys-su-avinzirniais.md
- _posts/2020-08-26-citrininis-pyragas-su-cukinija.md
- _posts/2020-08-30-keptas-kiaulienos-kumpis-su-prieskoniu-plutele.md
- _posts/2020-08-31-pieniska-darzoviu-ir-vistienos-sriuba.md
- _posts/2020-09-02-ant-grilio-keptu-cukiniju-ir-fetos-salotos.md
- _posts/2020-09-10-pomidoru-salotos-su-perlinemis-kruopomis-ir-feta.md
- _posts/2020-09-11-paprastos-pomidoru-salotos.md
- _posts/2020-09-12-kepti-svarainiai-su-maskarpones-suriu.md
- _posts/2020-09-14-trinta-pomidoru-sriuba.md
- _posts/2020-09-18-omletas-su-voveraitemis.md
- _posts/2020-09-20-grybu-sriuba-su-melynuoju-suriu.md
- _posts/2020-09-22-pomidoru-salotos-su-vytintu-kumpiu.md
- _posts/2020-09-23-cukiniju-ir-perliniu-kruopu-blynai.md
- _posts/2020-09-24-jautienos-koftos.md
- _posts/2020-10-05-namine-imbierine-arbata-1.md
- _posts/2020-10-05-rukytos-skumbres-salotos.md
- _posts/2020-10-10-kepti-burokeliai.md
- _posts/2020-10-10-kepti-ridikeliai.md
- _posts/2020-10-10-orkaiteje-kepti-ketvirciai-su-keptais-ridikeliais-ir-burokeliais.md
- _posts/2020-10-17-troskinys-su-jautienos-desrelemis.md
- _posts/darzoviu-sriuba-su-moliugu-ir-brokoliu.md
- _posts/kepti-brokoliai-su-anciuviais.md
- _posts/pacifloru-ir-zaliuju-citrinu-arbata.md
